import 'task_item.dart';

class Task {
  final int id;
  final String taskDate;
  final String? title;
  final String status;
  final bool autoGenerated;
  final List<TaskItem> items;
  final String? createdAt;
  final bool existing; // 自动生成时标识是否已有

  Task({
    required this.id,
    required this.taskDate,
    this.title,
    this.status = 'pending',
    this.autoGenerated = false,
    this.items = const [],
    this.createdAt,
    this.existing = false,
  });

  factory Task.fromJson(Map<String, dynamic> json) {
    return Task(
      id: json['id'] as int,
      taskDate: json['task_date'] as String? ?? '',
      title: json['title'] as String?,
      status: json['status'] as String? ?? 'pending',
      autoGenerated: (json['auto_generated'] as int?) == 1,
      items: (json['items'] as List<dynamic>?)
              ?.map((e) => TaskItem.fromJson(e as Map<String, dynamic>))
              .toList() ??
          [],
      createdAt: json['created_at'] as String?,
      existing: json['existing'] as bool? ?? false,
    );
  }

  int get pendingCount => items.where((i) => i.status == 'pending').length;
  int get doneCount => items.where((i) => i.status == 'done').length;
  int get totalCount => items.length;

  String get statusLabel {
    if (status == 'completed') return '已完成';
    if (totalCount == 0) return '无任务';
    if (doneCount == totalCount) return '全部完成';
    return '$doneCount/$totalCount';
  }
}
